import "tailwindcss/tailwind.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="bg-gradient-to-r from-purple via-blue to-ocean h-screen px-2 md:px-4"
    >
      <body>{children}</body>
    </html>
  );
}
